---
# defaults file for vsftpd

vsftpd_package: vsftpd
# users to create with nologin
vsftpd_users: []
# start on boot
vsftpd_service_enabled: yes
# current state: started, stopped
vsftpd_service_state: started
# enable ssl by default
